import type { AnalyticsEntry, ContentHubData, Idea, Post } from "@/lib/types";

const now = "2026-04-04T09:00:00-07:00";

const seedIdeas: Idea[] = [
  {
    id: "idea-ai-first-failing",
    title: "Why 'AI-first' companies are failing",
    description:
      "Pull apart the difference between distribution theater and compounding product advantage. Anchor it in the companies that optimized demos instead of retention.",
    platform: "linkedin",
    postType: "contrarian",
    priority: "high",
    status: "new",
    tags: ["distribution", "strategy"],
    createdAt: "2026-03-29T09:00:00-07:00",
    updatedAt: "2026-03-29T09:00:00-07:00",
    scheduledPostIds: [],
  },
  {
    id: "idea-claude-setup",
    title: "My actual Claude Code setup + config",
    description:
      "Break down prompts, MCP servers, and the habits that make it useful day to day. This should become the next premium Substack deep dive.",
    platform: "substack",
    postType: "paid-deep-dive",
    priority: "high",
    status: "developing",
    tags: ["claude-code", "workflow"],
    createdAt: "2026-03-27T11:30:00-07:00",
    updatedAt: "2026-04-01T14:00:00-07:00",
    scheduledPostIds: ["post-claude-setup"],
  },
  {
    id: "idea-tool-comparison",
    title: "Cursor vs Claude Code vs Copilot for teams",
    description:
      "A sharper comparison for engineering leaders. Focus on coordination cost, review surface, and where each tool breaks down.",
    platform: "linkedin",
    postType: "tool-review",
    priority: "medium",
    status: "new",
    tags: ["cursor", "copilot", "teams"],
    createdAt: "2026-03-30T08:20:00-07:00",
    updatedAt: "2026-03-30T08:20:00-07:00",
    scheduledPostIds: [],
  },
  {
    id: "idea-sprint-planning",
    title: "How I restructured sprint planning with AI",
    description:
      "One concept, two formats: short LinkedIn narrative plus a longer Substack teardown on the exact meeting ritual and artifacts.",
    platform: "both",
    postType: "trenches",
    priority: "medium",
    status: "new",
    tags: ["operations", "ai-teams"],
    createdAt: "2026-03-24T15:00:00-07:00",
    updatedAt: "2026-03-24T15:00:00-07:00",
    scheduledPostIds: [],
  },
  {
    id: "idea-top-developments",
    title: "Top 5 AI developments this week",
    description:
      "Recurring free roundup with one sharp take per item instead of generic summaries.",
    platform: "substack",
    postType: "free-roundup",
    priority: "low",
    status: "ready",
    tags: ["roundup", "weekly"],
    createdAt: "2026-04-02T07:45:00-07:00",
    updatedAt: "2026-04-02T07:45:00-07:00",
    scheduledPostIds: [],
  },
];

const seedPosts: Post[] = [
  {
    id: "post-lecun-dead-end",
    title: "Yann LeCun just raised $1.03 billion to prove LLMs are a dead end",
    content:
      "Yann LeCun just raised $1.03 billion for a research lab built on the thesis that LLMs are a dead end.\n\nMost people read this as academic drama. I think it is the most important capital allocation signal in AI right now.\n\nHere is why:\n\nThe money is not going to a bigger GPT. It is going to an entirely different architecture — one that reasons about the world through prediction and planning, not next-token generation.\n\nThat means the market is now funding alternatives to the current interface layer, not just incremental model scale.\n\nFor builders, this changes the calculus:\n\n→ If you are building on top of LLMs today, your moat is not the model. It is your data flywheel, your distribution, and your workflow integration.\n\n→ If the next wave of models reasons differently, the companies that survive will be the ones who built product value independent of any single architecture.\n\n→ The teams treating GPT-5 as their product strategy are playing the wrong game.\n\nThe real question is not whether LeCun is right. It is whether your product thesis survives if he is.\n\nThat is the signal founders and operators should be watching.\n\nWhat is your current model dependency? Would love to hear how others are thinking about this.",
    imageUrl: "/images/batch-1/copilot-infographic-chatgpt.png",
    platform: "linkedin",
    postType: "contrarian",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-15T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 16968, comments: 9, reposts: 1, reactions: 16, followerDelta: 72 },
    createdAt: "2026-03-12T07:45:00-07:00",
    updatedAt: "2026-03-15T10:00:00-07:00",
  },
  {
    id: "post-google-principal-engineer",
    title: "Google principal engineer: Claude Code produced what our team built in a year",
    content:
      "A Google principal engineer said Claude Code produced in one afternoon what his team built over a year.\n\nThe headline is provocative. But the useful lesson is narrower than people think.\n\nHere is what actually happened:\n\nThe engineer used Claude Code to scaffold a complete internal tool — routing logic, API layer, basic UI. The kind of project that usually takes a team months of sprint planning, code review, and incremental shipping.\n\nDoes that mean AI replaces engineering teams? No.\n\nIt means compressed iteration loops are starting to change what counts as normal output for strong engineering teams.\n\nThe implications for leaders:\n\n1. Your planning assumptions about project timelines are probably wrong now. A senior engineer with good AI tooling can move 3-5x faster on greenfield work.\n\n2. Code review matters more, not less. Speed without quality control just means you ship bugs faster.\n\n3. The bottleneck is shifting from \"can we build it\" to \"should we build it\" and \"does it actually solve the problem.\"\n\n4. Junior engineers who learn to use these tools effectively will outperform seniors who refuse to.\n\nThe teams that figure out how to integrate AI into their existing engineering culture — not replace it — will compound their advantage every quarter.\n\nThe ones who ignore it will wonder why their competitors ship twice as fast.\n\nHow is your team adapting?",
    platform: "linkedin",
    postType: "trenches",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-22T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 11486, comments: 13, reposts: 2, followerDelta: 41 },
    createdAt: "2026-03-20T09:00:00-07:00",
    updatedAt: "2026-03-22T09:45:00-07:00",
  },
  {
    id: "post-ai-no-code-platforms",
    title: "AI no-code builders look magical. They're not. They're platforms.",
    content:
      "Every week I see another AI no-code builder launch with a demo that looks like magic.\n\nDrag, drop, describe what you want. App appears. Everyone claps.\n\nBut here is what nobody talks about:\n\nThese products are not replacing engineering. They are moving the platform boundary.\n\nAnd that distinction matters enormously if you care about three things:\n\n→ Control: When the platform decides how your app works under the hood, you lose the ability to optimize for your specific use case. Fine for prototypes. Dangerous for production.\n\n→ Pricing power: You are renting someone else's abstraction layer. When they raise prices — and they will — your margins shrink and you have no alternative.\n\n→ Migration cost: The more you build on a proprietary no-code surface, the harder it is to leave. Your \"code\" is not code. It is configuration trapped inside their system.\n\nI have seen this pattern before. It happened with Heroku. It happened with early WordPress hosting. It happened with Webflow.\n\nThe builders who understand they are choosing a platform, not just a tool, make better long-term decisions.\n\nThe ones who think they found a shortcut to engineering usually pay for it 18 months later.\n\nUse these tools for what they are good at: speed to prototype, validation, and internal tooling.\n\nJust do not confuse a demo with a product.",
    platform: "linkedin",
    postType: "contrarian",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-18T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 1978, comments: 5, reposts: 2, reactions: 11, followerDelta: 7 },
    createdAt: "2026-03-17T10:00:00-07:00",
    updatedAt: "2026-03-18T09:00:00-07:00",
  },
  {
    id: "post-engineering-jobs",
    title: "Engineering jobs are growing (despite AI)",
    content:
      "\"AI is going to replace all software engineers.\"\n\nI keep hearing this. The data says the opposite.\n\nEngineering job postings in Q1 2026 are up 12% year over year. Not down. Up.\n\nBut the composition is changing fast:\n\n→ Fewer roles for people who write boilerplate CRUD apps. Those tasks are genuinely getting automated.\n\n→ More roles for people who can architect systems, evaluate tradeoffs, and manage complexity that AI tools create.\n\n→ A new category emerging: engineers who are primarily AI tool operators. They do not write much code from scratch. They orchestrate, review, and integrate.\n\nThe hiring market is changing shape, not disappearing.\n\nTeams still need people who can reason about systems, risk, and leverage. They just need fewer people who can only write for-loops.\n\nIf you are an engineer worried about job security, here is my honest take:\n\n1. Learn to use AI coding tools deeply. Not the demo version. The real daily workflow.\n2. Invest in system design and architecture thinking. That is the last thing AI will replace.\n3. Get good at evaluating AI output. The skill gap is widening between people who blindly accept AI suggestions and people who critically assess them.\n\nThe engineers who adapt will be more valuable than ever. The ones who refuse will struggle.\n\nThat has always been true about technology shifts. This one is just faster.",
    platform: "linkedin",
    postType: "trenches",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-25T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 1748, comments: 1, reposts: 1, reactions: 8, followerDelta: 5 },
    createdAt: "2026-03-24T16:00:00-07:00",
    updatedAt: "2026-03-25T08:30:00-07:00",
  },
  {
    id: "post-slack-mcp",
    title: "The Slack MCP setup that changed my morning routine",
    content:
      "I used to start every morning the same way:\n\nOpen Slack. Scroll through 47 unread messages. Try to figure out what actually matters. Spend 30 minutes context-switching before doing any real work.\n\nThen I set up an MCP server connected to Slack, and everything changed.\n\nHere is the setup:\n\n→ MCP server reads my Slack channels overnight and creates a structured briefing: decisions made, questions asked, blockers raised, and action items assigned to me.\n\n→ I get a 2-minute summary instead of a 30-minute scroll session.\n\n→ My AI assistant can now reference Slack context when I ask it questions about projects. \"What did the team decide about the API migration?\" Just works.\n\nThe results after 3 weeks:\n\n• Morning context loading went from ~30 minutes to ~5 minutes\n• I stopped missing important threads buried in noisy channels\n• My first deep work block starts at 8:15 instead of 9:00\n\nThe value was not automation for its own sake. It was getting the right context bundled before I started writing or replying.\n\nThe setup took about 2 hours. The compound time savings over a month are probably 8-10 hours.\n\nIf you are drowning in Slack, this is the highest-leverage MCP use case I have found so far.\n\nHappy to share the config if anyone wants to try it.",
    platform: "linkedin",
    postType: "tool-review",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-20T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 1591, comments: 0, reposts: 0, reactions: 6, followerDelta: 4 },
    createdAt: "2026-03-19T08:00:00-07:00",
    updatedAt: "2026-03-20T08:30:00-07:00",
  },
  {
    id: "post-switching-to-claude",
    title: "Anthropic is at it again — switching from ChatGPT to Claude",
    content:
      "I switched from ChatGPT to Claude 3 months ago.\n\nNot because of benchmarks. Not because of Twitter hype. Because of one specific workflow difference.\n\nHere is what happened:\n\nI was using ChatGPT for code review and technical writing. It was fine. Good even. But I kept running into the same friction: the model would give me confident, plausible answers that were subtly wrong in ways that took time to catch.\n\nClaude handled the same tasks differently. It would flag its own uncertainty. It would say \"I am not sure about this part\" instead of confidently hallucinating.\n\nFor my workflow — where I need to trust the output enough to ship it — that difference in calibration was worth more than any benchmark improvement.\n\n3 months in, here is my honest assessment:\n\n→ Claude is better for: long-form writing, code review, nuanced technical analysis, and tasks where calibrated uncertainty matters.\n\n→ ChatGPT is better for: quick lookups, creative brainstorming, and tasks where you want the model to be maximally generative.\n\n→ Neither is \"better.\" They are different tools for different jobs.\n\nPeople frame model choices like ideology. In practice, most teams switch when workflow fit beats habit.\n\nThe interesting question is not which model is best. It is which model fits the specific job you are hiring it for.\n\nWhat model are you using daily, and why did you choose it?",
    platform: "linkedin",
    postType: "tool-review",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-28T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 1533, comments: 5, reposts: 0, reactions: 9, followerDelta: 3 },
    createdAt: "2026-03-27T12:00:00-07:00",
    updatedAt: "2026-03-28T09:00:00-07:00",
  },
  {
    id: "post-claude-setup",
    ideaId: "idea-claude-setup",
    title: "My actual Claude Code setup + config",
    content:
      "I stopped treating Claude Code like a chatbot and started treating it like a command surface. That single mindset shift changed everything about my daily output.\n\nHere is my exact setup:\n\n## The Stack\n\n• MCP server for Slack context — so Claude can reference team discussions without me copy-pasting\n• Project memory notes in CLAUDE.md — persistent context that survives across sessions\n• Structured review loop — every patch gets a 60-second manual review before commit\n• Custom system prompt tuned for my codebase conventions\n\n## The Morning Workflow\n\nBefore: Open IDE → read through PRs → context-switch between Slack and code → start writing code around 10am.\n\nAfter: Open Claude Code → ask \"what needs attention today based on open PRs and Slack threads\" → get a prioritized list → start shipping by 8:30am.\n\nThe difference is roughly 90 minutes of productive time recovered every morning.\n\n## Why It Works\n\nThe system is boring, repeatable, and reduces context loss. That is exactly why it compounds.\n\nMost people use AI coding tools like a magic 8-ball: ask a question, hope for a good answer. The ones who get real value treat it like a junior engineer with perfect memory — give it context, give it constraints, review its work.\n\n## The Numbers\n\n• Code review time: down ~40%\n• First commit of the day: moved from 10am to 8:30am\n• Bugs caught before merge: up noticeably (hard to quantify exactly)\n• Time spent context-switching: cut roughly in half\n\nThe setup took me about a weekend to dial in. The compound effect over a month is significant.\n\nFull config files and prompt templates are in the paid version of this post for subscribers who want to replicate it.",
    imageUrl: "/images/batch-1/copilot-map-cropped.png",
    platform: "substack",
    postType: "paid-deep-dive",
    status: "review",
    approvalStatus: "pending",
    scheduledAt: "2026-04-08T09:00:00-07:00",
    comments: [
      {
        id: "comment-claude-setup-1",
        text: "Add one concrete before/after example from your morning workflow.",
        author: "zima",
        createdAt: "2026-04-02T09:30:00-07:00",
      },
    ],
    revisions: [
      {
        id: "revision-claude-setup-1",
        content:
          "Initial draft focused too much on setup screenshots and not enough on the workflow shift.",
        createdAt: "2026-04-01T12:00:00-07:00",
      },
    ],
    createdAt: "2026-04-01T08:00:00-07:00",
    updatedAt: "2026-04-02T09:30:00-07:00",
  },
  {
    id: "post-founder-content-engine",
    title: "Your content engine is a product surface, not a side project",
    content:
      "Most founders treat content like a checkbox.\n\n\"We should probably post on LinkedIn.\" So they write something once a week when they remember. No system. No process. No feedback loop.\n\nHere is why that is a strategic mistake:\n\nYour content engine is not a marketing channel. It is a product surface.\n\nEvery post you publish does three things:\n\n1. It tests a message with your target audience in real time. Better than any survey or focus group.\n\n2. It builds compounding distribution. Every follower, every subscriber, every share is an asset that makes your next launch cheaper.\n\n3. It creates a feedback loop that improves your product thinking. When you write about your space regularly, you notice patterns faster.\n\nThe founders I know who take content seriously — not as influencers, but as operators — consistently make better product decisions.\n\nBecause they are in conversation with their market every single week.\n\nThe ones who treat it as a side project get inconsistent output, weak signal capture, and wonder why their launches feel like shouting into the void.\n\nHere is the minimum viable system:\n\n→ 3 posts per week on your primary platform\n→ 1 longer piece per week on a secondary platform\n→ A 30-minute weekly review of what performed and why\n→ A running list of ideas captured from customer conversations\n\nThat is it. No content team needed. No viral strategy required.\n\nJust consistency, feedback, and compound interest.\n\nAre you building a content engine or just posting when you remember?",
    imageUrl: "/images/batch-1/codex-terminal-cropped.png",
    platform: "linkedin",
    postType: "trenches",
    status: "draft",
    approvalStatus: "pending",
    scheduledAt: "2026-04-07T08:15:00-07:00",
    comments: [],
    revisions: [],
    createdAt: "2026-04-03T10:00:00-07:00",
    updatedAt: "2026-04-03T10:00:00-07:00",
  },
  {
    id: "post-free-roundup-april",
    title: "Top 5 AI developments this week",
    content:
      "Five things that caught my attention this week in AI. No hype, just signal.\n\n1. Model routing is getting more opinionated\n\nOpenRouter, Martian, and others are building smarter routing layers that pick the best model per task automatically. This matters because it means your product does not need to bet on a single provider anymore. The abstraction layer is becoming the product.\n\n2. Tooling vendors are bundling evals\n\nLangSmith, Braintrust, and Humanloop all shipped eval features this month. The message is clear: if you are not measuring output quality systematically, you are falling behind. Evals are moving from \"nice to have\" to table stakes.\n\n3. Enterprise buyers are asking harder questions about data ownership\n\nTwo CTO conversations this week both centered on the same concern: \"Where does our data go when we use your AI features?\" The honeymoon phase of enterprise AI adoption is ending. Due diligence is catching up.\n\n4. Open-source models are closing the gap faster than expected\n\nLlama 4 Scout benchmarks are competitive with GPT-4o on most practical tasks. For teams building on open-source, the cost-performance curve just shifted significantly in their favor.\n\n5. AI coding tools are fragmenting into specialized niches\n\nCursor for frontend, Claude Code for backend architecture, Copilot for quick completions. The \"one tool to rule them all\" phase is over. Teams are building multi-tool workflows.\n\nBiggest takeaway: The infrastructure layer is maturing fast. If you are building AI products, the foundational pieces are getting cheaper and more reliable every month. The differentiation is moving to product design and distribution.\n\nWhat caught your attention this week?",
    platform: "substack",
    postType: "free-roundup",
    status: "approved",
    approvalStatus: "approved",
    scheduledAt: "2026-04-10T07:30:00-07:00",
    comments: [],
    revisions: [],
    createdAt: now,
    updatedAt: now,
  },
];

const seedAnalytics: AnalyticsEntry[] = [
  { date: "2026-03-15", linkedinFollowers: 12912, substackSubscribers: 8 },
  { date: "2026-03-18", linkedinFollowers: 12919, substackSubscribers: 8 },
  { date: "2026-03-20", linkedinFollowers: 12923, substackSubscribers: 9 },
  { date: "2026-03-22", linkedinFollowers: 12964, substackSubscribers: 9 },
  { date: "2026-03-25", linkedinFollowers: 12969, substackSubscribers: 10 },
  { date: "2026-03-28", linkedinFollowers: 12972, substackSubscribers: 11 },
  { date: "2026-03-31", linkedinFollowers: 13004, substackSubscribers: 12 },
  { date: "2026-04-02", linkedinFollowers: 13028, substackSubscribers: 13 },
  { date: "2026-04-04", linkedinFollowers: 13045, substackSubscribers: 14 },
];

export const seedContentHubData: ContentHubData = {
  ideas: seedIdeas,
  posts: seedPosts,
  analytics: seedAnalytics,
  settings: {
    theme: "system",
    postingSchedule: {
      linkedin: [1, 3, 5],
      substack: [2, 4],
    },
    notificationsEnabled: false,
  },
};
