import type { AnalyticsEntry, ContentHubData, Idea, Post } from "@/lib/types";

const now = "2026-04-04T09:00:00-07:00";

const seedIdeas: Idea[] = [
  {
    id: "idea-ai-first-failing",
    title: "Why 'AI-first' companies are failing",
    description:
      "Pull apart the difference between distribution theater and compounding product advantage. Anchor it in the companies that optimized demos instead of retention.",
    platform: "linkedin",
    postType: "contrarian",
    priority: "high",
    status: "new",
    tags: ["distribution", "strategy"],
    createdAt: "2026-03-29T09:00:00-07:00",
    updatedAt: "2026-03-29T09:00:00-07:00",
    scheduledPostIds: [],
  },
  {
    id: "idea-claude-setup",
    title: "My actual Claude Code setup + config",
    description:
      "Break down prompts, MCP servers, and the habits that make it useful day to day. This should become the next premium Substack deep dive.",
    platform: "substack",
    postType: "paid-deep-dive",
    priority: "high",
    status: "developing",
    tags: ["claude-code", "workflow"],
    createdAt: "2026-03-27T11:30:00-07:00",
    updatedAt: "2026-04-01T14:00:00-07:00",
    scheduledPostIds: ["post-claude-setup"],
  },
  {
    id: "idea-tool-comparison",
    title: "Cursor vs Claude Code vs Copilot for teams",
    description:
      "A sharper comparison for engineering leaders. Focus on coordination cost, review surface, and where each tool breaks down.",
    platform: "linkedin",
    postType: "tool-review",
    priority: "medium",
    status: "new",
    tags: ["cursor", "copilot", "teams"],
    createdAt: "2026-03-30T08:20:00-07:00",
    updatedAt: "2026-03-30T08:20:00-07:00",
    scheduledPostIds: [],
  },
  {
    id: "idea-sprint-planning",
    title: "How I restructured sprint planning with AI",
    description:
      "One concept, two formats: short LinkedIn narrative plus a longer Substack teardown on the exact meeting ritual and artifacts.",
    platform: "both",
    postType: "trenches",
    priority: "medium",
    status: "new",
    tags: ["operations", "ai-teams"],
    createdAt: "2026-03-24T15:00:00-07:00",
    updatedAt: "2026-03-24T15:00:00-07:00",
    scheduledPostIds: [],
  },
  {
    id: "idea-top-developments",
    title: "Top 5 AI developments this week",
    description:
      "Recurring free roundup with one sharp take per item instead of generic summaries.",
    platform: "substack",
    postType: "free-roundup",
    priority: "low",
    status: "ready",
    tags: ["roundup", "weekly"],
    createdAt: "2026-04-02T07:45:00-07:00",
    updatedAt: "2026-04-02T07:45:00-07:00",
    scheduledPostIds: [],
  },
];

const seedPosts: Post[] = [
  {
    id: "post-lecun-dead-end",
    title: "Yann LeCun just raised $1.03 billion to prove LLMs are a dead end",
    content:
      "The interesting part is not the headline. It is that the market is now funding alternatives to the current interface layer, not just incremental model scale.\n\nThat is the real signal creators and operators should watch.",
    imageUrl: "/images/batch-1/copilot-infographic-chatgpt.png",
    platform: "linkedin",
    postType: "contrarian",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-15T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 16968, comments: 9, reposts: 1, reactions: 16, followerDelta: 72 },
    createdAt: "2026-03-12T07:45:00-07:00",
    updatedAt: "2026-03-15T10:00:00-07:00",
  },
  {
    id: "post-google-principal-engineer",
    title: "Google principal engineer: Claude Code produced what our team built in a year",
    content:
      "The headline is provocative, but the useful lesson is narrower: compressed iteration loops are starting to change what counts as normal output for strong engineering teams.",
    platform: "linkedin",
    postType: "trenches",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-22T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 11486, comments: 13, reposts: 2, followerDelta: 41 },
    createdAt: "2026-03-20T09:00:00-07:00",
    updatedAt: "2026-03-22T09:45:00-07:00",
  },
  {
    id: "post-ai-no-code-platforms",
    title: "AI no-code builders look magical. They're not. They're platforms.",
    content:
      "Most of these products are not replacing engineering. They are moving the platform boundary. That matters if you care about control, pricing power, and migration cost.",
    platform: "linkedin",
    postType: "contrarian",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-18T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 1978, comments: 5, reposts: 2, reactions: 11, followerDelta: 7 },
    createdAt: "2026-03-17T10:00:00-07:00",
    updatedAt: "2026-03-18T09:00:00-07:00",
  },
  {
    id: "post-engineering-jobs",
    title: "Engineering jobs are growing (despite AI)",
    content:
      "The hiring market is changing shape, not disappearing. Teams still need people who can reason about systems, risk, and leverage.",
    platform: "linkedin",
    postType: "trenches",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-25T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 1748, comments: 1, reposts: 1, reactions: 8, followerDelta: 5 },
    createdAt: "2026-03-24T16:00:00-07:00",
    updatedAt: "2026-03-25T08:30:00-07:00",
  },
  {
    id: "post-slack-mcp",
    title: "The Slack MCP setup that changed my morning routine",
    content:
      "The value was not automation for its own sake. It was getting the right context bundled before I started writing or replying.",
    platform: "linkedin",
    postType: "tool-review",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-20T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 1591, comments: 0, reposts: 0, reactions: 6, followerDelta: 4 },
    createdAt: "2026-03-19T08:00:00-07:00",
    updatedAt: "2026-03-20T08:30:00-07:00",
  },
  {
    id: "post-switching-to-claude",
    title: "Anthropic is at it again — switching from ChatGPT to Claude",
    content:
      "People frame model choices like ideology. In practice, most teams switch when workflow fit beats habit.",
    platform: "linkedin",
    postType: "tool-review",
    status: "posted",
    approvalStatus: "approved",
    scheduledAt: "2026-03-28T08:00:00-07:00",
    comments: [],
    revisions: [],
    metrics: { impressions: 1533, comments: 5, reposts: 0, reactions: 9, followerDelta: 3 },
    createdAt: "2026-03-27T12:00:00-07:00",
    updatedAt: "2026-03-28T09:00:00-07:00",
  },
  {
    id: "post-claude-setup",
    ideaId: "idea-claude-setup",
    title: "My actual Claude Code setup + config",
    content:
      "## What changed\nI stopped treating Claude Code like a chatbot and started treating it like a command surface.\n\n## Stack\n- MCP server for Slack context\n- Standard project memory notes\n- Tight review loop for patches\n\n## Why it works\nThe system is boring, repeatable, and reduces context loss.",
    imageUrl: "/images/batch-1/copilot-map-cropped.png",
    platform: "substack",
    postType: "paid-deep-dive",
    status: "review",
    approvalStatus: "pending",
    scheduledAt: "2026-04-08T09:00:00-07:00",
    comments: [
      {
        id: "comment-claude-setup-1",
        text: "Add one concrete before/after example from your morning workflow.",
        author: "zima",
        createdAt: "2026-04-02T09:30:00-07:00",
      },
    ],
    revisions: [
      {
        id: "revision-claude-setup-1",
        content:
          "Initial draft focused too much on setup screenshots and not enough on the workflow shift.",
        createdAt: "2026-04-01T12:00:00-07:00",
      },
    ],
    createdAt: "2026-04-01T08:00:00-07:00",
    updatedAt: "2026-04-02T09:30:00-07:00",
  },
  {
    id: "post-founder-content-engine",
    title: "Your content engine is a product surface, not a side project",
    content:
      "Founders who treat content as a side channel underinvest in process. The result is inconsistent output and weak signal capture.",
    imageUrl: "/images/batch-1/codex-terminal-cropped.png",
    platform: "linkedin",
    postType: "trenches",
    status: "draft",
    approvalStatus: "pending",
    scheduledAt: "2026-04-07T08:15:00-07:00",
    comments: [],
    revisions: [],
    createdAt: "2026-04-03T10:00:00-07:00",
    updatedAt: "2026-04-03T10:00:00-07:00",
  },
  {
    id: "post-free-roundup-april",
    title: "Top 5 AI developments this week",
    content:
      "1. Model routing got more opinionated.\n2. Tooling vendors are bundling evals into the product.\n3. Enterprise buyers are asking harder questions about ownership.\n\nShort take after each item.",
    platform: "substack",
    postType: "free-roundup",
    status: "approved",
    approvalStatus: "approved",
    scheduledAt: "2026-04-10T07:30:00-07:00",
    comments: [],
    revisions: [],
    createdAt: now,
    updatedAt: now,
  },
];

const seedAnalytics: AnalyticsEntry[] = [
  { date: "2026-03-15", linkedinFollowers: 12912, substackSubscribers: 8 },
  { date: "2026-03-18", linkedinFollowers: 12919, substackSubscribers: 8 },
  { date: "2026-03-20", linkedinFollowers: 12923, substackSubscribers: 9 },
  { date: "2026-03-22", linkedinFollowers: 12964, substackSubscribers: 9 },
  { date: "2026-03-25", linkedinFollowers: 12969, substackSubscribers: 10 },
  { date: "2026-03-28", linkedinFollowers: 12972, substackSubscribers: 11 },
  { date: "2026-03-31", linkedinFollowers: 13004, substackSubscribers: 12 },
  { date: "2026-04-02", linkedinFollowers: 13028, substackSubscribers: 13 },
  { date: "2026-04-04", linkedinFollowers: 13045, substackSubscribers: 14 },
];

export const seedContentHubData: ContentHubData = {
  ideas: seedIdeas,
  posts: seedPosts,
  analytics: seedAnalytics,
  settings: {
    theme: "system",
    postingSchedule: {
      linkedin: [1, 3, 5],
      substack: [2, 4],
    },
    notificationsEnabled: false,
  },
};
